version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: kampungkaki_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kampung_user
      POSTGRES_PASSWORD: kampung_pass
      POSTGRES_DB: kampung_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
